onlyBuiltDependencies: []

minimumReleaseAgeExclude:
  - '@graphql-codegen/client-preset@6.1.3'
  - '@graphql-codegen/typescript-operations@6.1.6'
  - '@graphql-codegen/visitor-plugin-common@7.2.5'

peerDependencyRules:
  allowedVersions:
    'graphql-config@5.1.6>graphql': '17'
