import { fileURLToPath, URL } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { offlineShellPlugin } from "./src/app/pwa/build-plugin.ts";
import { emojiDataPlugin } from "./src/features/task-discussion/emoji-build-plugin.ts";

export default defineConfig({
  plugins: [
    tanstackRouter({
      target: "react",
      autoCodeSplitting: true,
      routeTreeFileHeader: ["/* biome-ignore-all lint: generated by TanStack Router */"],
    }),
    react(),
    tailwindcss(),
    offlineShellPlugin(),
    emojiDataPlugin(),
  ],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  build: {
    outDir: "../internal/web/assets/dist",
    emptyOutDir: true,
  },
});
