// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CompleteTaskInput struct {
	CsrfToken    string   `json:"csrfToken"`
	TaskID       string   `json:"taskId"`
	ExpectedKind TaskKind `json:"expectedKind"`
}

type CompletionPayload struct {
	Status               CompletionStatus `json:"status"`
	CompletedTask        *Task            `json:"completedTask,omitempty"`
	NextOccurrence       *Task            `json:"nextOccurrence,omitempty"`
	UndoUntil            *time.Time       `json:"undoUntil,omitempty"`
	UndoCapability       *string          `json:"undoCapability,omitempty"`
	RepairCapability     *string          `json:"repairCapability,omitempty"`
	MissingMarkers       []MarkerKind     `json:"missingMarkers"`
	RemainingRepairSteps []RepairStep     `json:"remainingRepairSteps"`
}

type CreateJobInput struct {
	CsrfToken               string        `json:"csrfToken"`
	Title                   *string       `json:"title,omitempty"`
	Description             *string       `json:"description,omitempty"`
	ProjectID               string        `json:"projectId"`
	Priority                TaskPriority  `json:"priority"`
	StartAt                 LocalDateTime `json:"startAt"`
	DurationMinutes         int           `json:"durationMinutes"`
	CompletionWindowMinutes int           `json:"completionWindowMinutes"`
}

type CreateOneTimeTaskInput struct {
	CsrfToken   string       `json:"csrfToken"`
	Title       string       `json:"title"`
	Description *string      `json:"description,omitempty"`
	ProjectID   string       `json:"projectId"`
	Priority    TaskPriority `json:"priority"`
	DueDate     *LocalDate   `json:"dueDate,omitempty"`
	DueTime     *LocalTime   `json:"dueTime,omitempty"`
}

type CreateRecurringTaskInput struct {
	CsrfToken    string         `json:"csrfToken"`
	Title        string         `json:"title"`
	Description  *string        `json:"description,omitempty"`
	ProjectID    string         `json:"projectId"`
	Priority     TaskPriority   `json:"priority"`
	FirstDueDate LocalDate      `json:"firstDueDate"`
	DueTime      *LocalTime     `json:"dueTime,omitempty"`
	Interval     int            `json:"interval"`
	Unit         RecurrenceUnit `json:"unit"`
	Mode         RecurrenceMode `json:"mode"`
}

type CreatorDiagnostic struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Name     string `json:"name"`
}

type DeleteTaskInput struct {
	CsrfToken string `json:"csrfToken"`
	TaskID    string `json:"taskId"`
}

type DeleteTaskPayload struct {
	DeletedTaskID string `json:"deletedTaskId"`
}

type Label struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginPayload struct {
	Session *Session `json:"session"`
}

type LogoutPayload struct {
	Authenticated bool `json:"authenticated"`
}

type Mutation struct {
}

type Project struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	IsDefault bool   `json:"isDefault"`
}

type ProjectResult struct {
	Items []*Project `json:"items"`
}

type Query struct {
}

type RecurrenceRule struct {
	Interval int            `json:"interval"`
	Unit     RecurrenceUnit `json:"unit"`
	Mode     RecurrenceMode `json:"mode"`
}

type RepairTaskMetadataInput struct {
	CsrfToken  string `json:"csrfToken"`
	Capability string `json:"capability"`
}

type Session struct {
	Authenticated bool         `json:"authenticated"`
	CsrfToken     *string      `json:"csrfToken,omitempty"`
	ExpiresAt     *time.Time   `json:"expiresAt,omitempty"`
	VikunjaUser   *VikunjaUser `json:"vikunjaUser,omitempty"`
}

type SkipRecurringTaskInput struct {
	CsrfToken string `json:"csrfToken"`
	TaskID    string `json:"taskId"`
}

type Task struct {
	ID                string             `json:"id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Kind              TaskKind           `json:"kind"`
	IsDone            bool               `json:"isDone"`
	DoneAt            *time.Time         `json:"doneAt,omitempty"`
	CompletionOutcome *CompletionOutcome `json:"completionOutcome,omitempty"`
	Project           *Project           `json:"project"`
	Priority          TaskPriority       `json:"priority"`
	DueAt             *time.Time         `json:"dueAt,omitempty"`
	HasDueTime        bool               `json:"hasDueTime"`
	StartAt           *time.Time         `json:"startAt,omitempty"`
	EndAt             *time.Time         `json:"endAt,omitempty"`
	RecurrenceRule    *RecurrenceRule    `json:"recurrenceRule,omitempty"`
	Labels            []*Label           `json:"labels"`
	IsOverdue         bool               `json:"isOverdue"`
	Timezone          string             `json:"timezone"`
}

type TaskDiagnostics struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"projectId"`
	Title          string             `json:"title"`
	Kind           TaskKind           `json:"kind"`
	IsDone         bool               `json:"isDone"`
	DoneAt         *time.Time         `json:"doneAt,omitempty"`
	DueAt          *time.Time         `json:"dueAt,omitempty"`
	StartAt        *time.Time         `json:"startAt,omitempty"`
	EndAt          *time.Time         `json:"endAt,omitempty"`
	Priority       TaskPriority       `json:"priority"`
	RecurrenceRule *RecurrenceRule    `json:"recurrenceRule,omitempty"`
	Labels         []*Label           `json:"labels"`
	CreatedAt      time.Time          `json:"createdAt"`
	UpdatedAt      time.Time          `json:"updatedAt"`
	Creator        *CreatorDiagnostic `json:"creator,omitempty"`
	MaxPermission  *string            `json:"maxPermission,omitempty"`
}

type TaskListInput struct {
	Scope     TaskScope `json:"scope"`
	ProjectID *string   `json:"projectId,omitempty"`
	Page      int       `json:"page"`
	PageSize  int       `json:"pageSize"`
}

type TaskMutationPayload struct {
	Task                 *Task              `json:"task"`
	Status               TaskMutationStatus `json:"status"`
	MissingMarkers       []MarkerKind       `json:"missingMarkers"`
	RemainingRepairSteps []RepairStep       `json:"remainingRepairSteps"`
	RepairCapability     *string            `json:"repairCapability,omitempty"`
}

type TaskPage struct {
	Items      []*Task          `json:"items"`
	Page       int              `json:"page"`
	PageSize   int              `json:"pageSize"`
	TotalItems int              `json:"totalItems"`
	TotalPages int              `json:"totalPages"`
	HasMore    bool             `json:"hasMore"`
	IsComplete bool             `json:"isComplete"`
	Issues     []*TaskPageIssue `json:"issues"`
}

type TaskPageIssue struct {
	Code      PageIssueCode `json:"code"`
	Message   string        `json:"message"`
	ProjectID *string       `json:"projectId,omitempty"`
}

type UndoTaskCompletionInput struct {
	CsrfToken  string `json:"csrfToken"`
	Capability string `json:"capability"`
}

type VikunjaUser struct {
	ID               string  `json:"id"`
	Username         string  `json:"username"`
	Timezone         string  `json:"timezone"`
	WeekStart        int     `json:"weekStart"`
	DefaultProjectID *string `json:"defaultProjectId,omitempty"`
}

type CompletionOutcome string

const (
	CompletionOutcomeCompleted CompletionOutcome = "COMPLETED"
	CompletionOutcomeSkipped   CompletionOutcome = "SKIPPED"
)

var AllCompletionOutcome = []CompletionOutcome{
	CompletionOutcomeCompleted,
	CompletionOutcomeSkipped,
}

func (e CompletionOutcome) IsValid() bool {
	switch e {
	case CompletionOutcomeCompleted, CompletionOutcomeSkipped:
		return true
	}
	return false
}

func (e CompletionOutcome) String() string {
	return string(e)
}

func (e *CompletionOutcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompletionOutcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompletionOutcome", str)
	}
	return nil
}

func (e CompletionOutcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompletionOutcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompletionOutcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CompletionStatus string

const (
	CompletionStatusConfirmed               CompletionStatus = "CONFIRMED"
	CompletionStatusConfirmedRepairRequired CompletionStatus = "CONFIRMED_REPAIR_REQUIRED"
)

var AllCompletionStatus = []CompletionStatus{
	CompletionStatusConfirmed,
	CompletionStatusConfirmedRepairRequired,
}

func (e CompletionStatus) IsValid() bool {
	switch e {
	case CompletionStatusConfirmed, CompletionStatusConfirmedRepairRequired:
		return true
	}
	return false
}

func (e CompletionStatus) String() string {
	return string(e)
}

func (e *CompletionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompletionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompletionStatus", str)
	}
	return nil
}

func (e CompletionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompletionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompletionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MarkerKind string

const (
	MarkerKindJob               MarkerKind = "JOB"
	MarkerKindDateOnly          MarkerKind = "DATE_ONLY"
	MarkerKindRecurrenceHistory MarkerKind = "RECURRENCE_HISTORY"
	MarkerKindSkipped           MarkerKind = "SKIPPED"
)

var AllMarkerKind = []MarkerKind{
	MarkerKindJob,
	MarkerKindDateOnly,
	MarkerKindRecurrenceHistory,
	MarkerKindSkipped,
}

func (e MarkerKind) IsValid() bool {
	switch e {
	case MarkerKindJob, MarkerKindDateOnly, MarkerKindRecurrenceHistory, MarkerKindSkipped:
		return true
	}
	return false
}

func (e MarkerKind) String() string {
	return string(e)
}

func (e *MarkerKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MarkerKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MarkerKind", str)
	}
	return nil
}

func (e MarkerKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MarkerKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MarkerKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PageIssueCode string

const (
	PageIssueCodeResultSetTooLarge PageIssueCode = "RESULT_SET_TOO_LARGE"
	PageIssueCodeUpstreamPartial   PageIssueCode = "UPSTREAM_PARTIAL"
)

var AllPageIssueCode = []PageIssueCode{
	PageIssueCodeResultSetTooLarge,
	PageIssueCodeUpstreamPartial,
}

func (e PageIssueCode) IsValid() bool {
	switch e {
	case PageIssueCodeResultSetTooLarge, PageIssueCodeUpstreamPartial:
		return true
	}
	return false
}

func (e PageIssueCode) String() string {
	return string(e)
}

func (e *PageIssueCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PageIssueCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PageIssueCode", str)
	}
	return nil
}

func (e PageIssueCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PageIssueCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PageIssueCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RecurrenceMode string

const (
	RecurrenceModeFromCompletion RecurrenceMode = "FROM_COMPLETION"
	RecurrenceModeScheduledCycle RecurrenceMode = "SCHEDULED_CYCLE"
)

var AllRecurrenceMode = []RecurrenceMode{
	RecurrenceModeFromCompletion,
	RecurrenceModeScheduledCycle,
}

func (e RecurrenceMode) IsValid() bool {
	switch e {
	case RecurrenceModeFromCompletion, RecurrenceModeScheduledCycle:
		return true
	}
	return false
}

func (e RecurrenceMode) String() string {
	return string(e)
}

func (e *RecurrenceMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecurrenceMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecurrenceMode", str)
	}
	return nil
}

func (e RecurrenceMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecurrenceMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecurrenceMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RecurrenceUnit string

const (
	RecurrenceUnitDay   RecurrenceUnit = "DAY"
	RecurrenceUnitWeek  RecurrenceUnit = "WEEK"
	RecurrenceUnitMonth RecurrenceUnit = "MONTH"
)

var AllRecurrenceUnit = []RecurrenceUnit{
	RecurrenceUnitDay,
	RecurrenceUnitWeek,
	RecurrenceUnitMonth,
}

func (e RecurrenceUnit) IsValid() bool {
	switch e {
	case RecurrenceUnitDay, RecurrenceUnitWeek, RecurrenceUnitMonth:
		return true
	}
	return false
}

func (e RecurrenceUnit) String() string {
	return string(e)
}

func (e *RecurrenceUnit) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecurrenceUnit(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecurrenceUnit", str)
	}
	return nil
}

func (e RecurrenceUnit) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecurrenceUnit) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecurrenceUnit) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepairStep string

const (
	RepairStepCreateHistorySnapshot   RepairStep = "CREATE_HISTORY_SNAPSHOT"
	RepairStepAttachJob               RepairStep = "ATTACH_JOB"
	RepairStepAttachDateOnly          RepairStep = "ATTACH_DATE_ONLY"
	RepairStepAttachRecurrenceHistory RepairStep = "ATTACH_RECURRENCE_HISTORY"
	RepairStepAttachSkipped           RepairStep = "ATTACH_SKIPPED"
	RepairStepNormalizeDue            RepairStep = "NORMALIZE_DUE"
)

var AllRepairStep = []RepairStep{
	RepairStepCreateHistorySnapshot,
	RepairStepAttachJob,
	RepairStepAttachDateOnly,
	RepairStepAttachRecurrenceHistory,
	RepairStepAttachSkipped,
	RepairStepNormalizeDue,
}

func (e RepairStep) IsValid() bool {
	switch e {
	case RepairStepCreateHistorySnapshot, RepairStepAttachJob, RepairStepAttachDateOnly, RepairStepAttachRecurrenceHistory, RepairStepAttachSkipped, RepairStepNormalizeDue:
		return true
	}
	return false
}

func (e RepairStep) String() string {
	return string(e)
}

func (e *RepairStep) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepairStep(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepairStep", str)
	}
	return nil
}

func (e RepairStep) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepairStep) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepairStep) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskKind string

const (
	TaskKindOneTime   TaskKind = "ONE_TIME"
	TaskKindRecurring TaskKind = "RECURRING"
	TaskKindJob       TaskKind = "JOB"
	TaskKindInvalid   TaskKind = "INVALID"
)

var AllTaskKind = []TaskKind{
	TaskKindOneTime,
	TaskKindRecurring,
	TaskKindJob,
	TaskKindInvalid,
}

func (e TaskKind) IsValid() bool {
	switch e {
	case TaskKindOneTime, TaskKindRecurring, TaskKindJob, TaskKindInvalid:
		return true
	}
	return false
}

func (e TaskKind) String() string {
	return string(e)
}

func (e *TaskKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskKind", str)
	}
	return nil
}

func (e TaskKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskMutationStatus string

const (
	TaskMutationStatusConfirmed      TaskMutationStatus = "CONFIRMED"
	TaskMutationStatusRepairRequired TaskMutationStatus = "REPAIR_REQUIRED"
)

var AllTaskMutationStatus = []TaskMutationStatus{
	TaskMutationStatusConfirmed,
	TaskMutationStatusRepairRequired,
}

func (e TaskMutationStatus) IsValid() bool {
	switch e {
	case TaskMutationStatusConfirmed, TaskMutationStatusRepairRequired:
		return true
	}
	return false
}

func (e TaskMutationStatus) String() string {
	return string(e)
}

func (e *TaskMutationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskMutationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskMutationStatus", str)
	}
	return nil
}

func (e TaskMutationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskMutationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskMutationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskPriority string

const (
	TaskPriorityUnset  TaskPriority = "UNSET"
	TaskPriorityLow    TaskPriority = "LOW"
	TaskPriorityMedium TaskPriority = "MEDIUM"
	TaskPriorityHigh   TaskPriority = "HIGH"
	TaskPriorityUrgent TaskPriority = "URGENT"
	TaskPriorityDoNow  TaskPriority = "DO_NOW"
)

var AllTaskPriority = []TaskPriority{
	TaskPriorityUnset,
	TaskPriorityLow,
	TaskPriorityMedium,
	TaskPriorityHigh,
	TaskPriorityUrgent,
	TaskPriorityDoNow,
}

func (e TaskPriority) IsValid() bool {
	switch e {
	case TaskPriorityUnset, TaskPriorityLow, TaskPriorityMedium, TaskPriorityHigh, TaskPriorityUrgent, TaskPriorityDoNow:
		return true
	}
	return false
}

func (e TaskPriority) String() string {
	return string(e)
}

func (e *TaskPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskPriority", str)
	}
	return nil
}

func (e TaskPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskPriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskPriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskScope string

const (
	TaskScopeToday       TaskScope = "TODAY"
	TaskScopeWeek        TaskScope = "WEEK"
	TaskScopeMonth       TaskScope = "MONTH"
	TaskScopeJobs        TaskScope = "JOBS"
	TaskScopeUnscheduled TaskScope = "UNSCHEDULED"
	TaskScopeHistory     TaskScope = "HISTORY"
)

var AllTaskScope = []TaskScope{
	TaskScopeToday,
	TaskScopeWeek,
	TaskScopeMonth,
	TaskScopeJobs,
	TaskScopeUnscheduled,
	TaskScopeHistory,
}

func (e TaskScope) IsValid() bool {
	switch e {
	case TaskScopeToday, TaskScopeWeek, TaskScopeMonth, TaskScopeJobs, TaskScopeUnscheduled, TaskScopeHistory:
		return true
	}
	return false
}

func (e TaskScope) String() string {
	return string(e)
}

func (e *TaskScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskScope", str)
	}
	return nil
}

func (e TaskScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
