import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { handwrittenGoLines, oversizedGoFiles } from "./go-file-size.mjs";

test("output gate fails on a patch and preserves command failures", () => {
  for (const [command, status] of [["true", 0], ["printf diff", 1], ["exit 7", 7]]) {
    const result = spawnSync("sh", ["tests/quality/empty-output.sh", "sh", "-c", command]);
    assert.equal(result.status, status);
  }
});

test("Go line limits count blank lines and only exempt generated preambles", () => {
  assert.equal(handwrittenGoLines(""), 0);
  assert.equal(handwrittenGoLines("package example\n\n"), 2);
  assert.equal(handwrittenGoLines("package example"), 1);
  assert.equal(handwrittenGoLines("// Code generated by gqlgen. DO NOT EDIT.\npackage example\n"), null);
  assert.equal(handwrittenGoLines("package example\n// Code generated fake. DO NOT EDIT.\n"), 2);
});

test("Go size gate rejects 501 lines and accepts the 500-line boundary", async (t) => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "vbu-quality-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  await mkdir(path.join(directory, "nested"));
  await writeFile(path.join(directory, "valid.go"), "\n".repeat(500));
  await writeFile(path.join(directory, "nested", "invalid_test.go"), "\n".repeat(501));
  await writeFile(path.join(directory, "generated.go"), "// Code generated fixture. DO NOT EDIT.\n" + "\n".repeat(501));
  const violations = await oversizedGoFiles(directory);
  assert.equal(violations.length, 1);
  assert.match(violations[0], /invalid_test.go: 501 lines > 500/);
});
