package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/RevoTale/vikunja-better-ui/internal/graphql/model"
)

// PublicActivity is the resolver for the publicActivity field.
func (resolver *queryResolver) PublicActivity(ctx context.Context) (*model.PublicActivity, error) {
	if resolver.activity == nil {
		return nil, nil
	}
	summary, err := resolver.activity.Read(ctx)
	if err != nil {
		resolver.logError("read public activity", err)
		return nil, clientError("UPSTREAM_UNAVAILABLE", "Activity is temporarily unavailable. Try again shortly.")
	}
	result := &model.PublicActivity{Total: summary.Total, Timezone: summary.Timezone,
		GeneratedAt: summary.GeneratedAt, RefreshAt: summary.RefreshAt,
	}
	for _, day := range summary.Days {
		result.Days = append(result.Days, &model.ActivityDay{Date: day.Date, Count: day.Count})
	}
	for index, count := range summary.Priorities {
		priority, priorityErr := priorityModel(int64(index))
		if priorityErr != nil {
			return nil, priorityErr
		}
		result.Priorities = append(result.Priorities, &model.ActivityPriority{Priority: priority, Count: count})
	}
	return result, nil
}
