package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/RevoTale/vikunja-better-ui/internal/vikunja"
)

// DiscussionAvatar is the resolver for the discussionAvatar field.
func (r *queryResolver) DiscussionAvatar(ctx context.Context, username string) (*string, error) {
	if _, err := requireSession(ctx); err != nil {
		return nil, err
	}
	value, err := r.avatars.Avatar(ctx, username)
	if errors.Is(err, vikunja.ErrInvalidAvatarUsername) {
		return nil, clientError("VALIDATION_FAILED", "Avatar username is invalid.")
	}
	if err != nil {
		r.logError("discussion avatar unavailable", err)
		return nil, nil
	}
	return &value, nil
}
