package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"strings"

	"github.com/RevoTale/vikunja-better-ui/internal/graphql/model"
	"github.com/RevoTale/vikunja-better-ui/internal/service"
	"github.com/RevoTale/vikunja-better-ui/internal/vikunja"
)

// CreateTaskComment is the resolver for the createTaskComment field.
func (r *mutationResolver) CreateTaskComment(ctx context.Context, input model.CreateTaskCommentInput) (*model.TaskComment, error) {
	if _, err := r.requireCSRF(ctx, input.CsrfToken); err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(input.TaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	write, err := commentWrite(input.BodyHTML)
	if err != nil {
		return nil, err
	}
	comment, err := r.comments.CreateTaskComment(ctx, taskID, write)
	if err != nil {
		return nil, r.discussionError(err, "The comment could not be confirmed. Refresh the discussion before retrying to avoid duplicates.")
	}
	return savedCommentModel(comment), nil
}

// UpdateTaskComment is the resolver for the updateTaskComment field.
func (r *mutationResolver) UpdateTaskComment(ctx context.Context, input model.UpdateTaskCommentInput) (*model.TaskComment, error) {
	if _, err := r.requireCSRF(ctx, input.CsrfToken); err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(input.TaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	commentID, err := parsePositiveID(input.CommentID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Comment ID is invalid.")
	}
	write, err := commentWrite(input.BodyHTML)
	if err != nil {
		return nil, err
	}
	comment, err := r.comments.UpdateTaskComment(ctx, taskID, commentID, write)
	if err != nil {
		return nil, r.discussionError(err, "The comment update could not be confirmed. Your text is preserved; refresh before retrying.")
	}
	return savedCommentModel(comment), nil
}

// DeleteTaskComment is the resolver for the deleteTaskComment field.
func (r *mutationResolver) DeleteTaskComment(ctx context.Context, input model.DeleteTaskCommentInput) (*model.DeleteTaskCommentPayload, error) {
	if _, err := r.requireCSRF(ctx, input.CsrfToken); err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(input.TaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	commentID, err := parsePositiveID(input.CommentID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Comment ID is invalid.")
	}
	if err := r.comments.DeleteTaskComment(ctx, taskID, commentID); err != nil {
		return nil, r.discussionError(err, "The comment deletion could not be confirmed. Refresh the discussion.")
	}
	return &model.DeleteTaskCommentPayload{DeletedCommentID: input.CommentID}, nil
}

// TaskComment is the resolver for the taskComment field.
func (r *queryResolver) TaskComment(ctx context.Context, taskID string, commentID string) (*model.TaskComment, error) {
	if _, err := requireSession(ctx); err != nil {
		return nil, err
	}
	task, err := parsePositiveID(taskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	comment, err := parsePositiveID(commentID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Comment ID is invalid.")
	}
	result, err := r.comments.TaskComment(ctx, task, comment)
	if err != nil {
		return nil, r.discussionError(err, "The original comment could not be loaded.")
	}
	return savedCommentModel(result), nil
}

// TaskComments is the resolver for the taskComments field.
func (r *queryResolver) TaskComments(ctx context.Context, taskID string, page int, pageSize int, order model.DiscussionOrder) (*model.TaskCommentPage, error) {
	if _, err := requireSession(ctx); err != nil {
		return nil, err
	}
	id, err := parsePositiveID(taskID)
	if err != nil || page < 1 || pageSize < 1 || pageSize > 100 || !order.IsValid() {
		return nil, clientError("VALIDATION_FAILED", "Choose a valid task, page, order and page size (1–100).")
	}
	result, err := service.LoadTaskDiscussion(ctx, r.comments, id, vikunja.CommentQuery{Page: int64(page), PerPage: int64(pageSize), Order: strings.ToLower(string(order))})
	if err != nil {
		return nil, r.discussionError(err, "Comments could not be loaded.")
	}
	return discussionPageModel(result)
}
