package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"math"

	"github.com/RevoTale/vikunja-better-ui/internal/graphql/model"
	"github.com/RevoTale/vikunja-better-ui/internal/service"
)

// UploadTaskMedia is the resolver for the uploadTaskMedia field.
func (r *mutationResolver) UploadTaskMedia(
	ctx context.Context, input model.UploadTaskMediaInput,
) (*model.TaskAttachment, error) {
	if _, err := r.requireCSRF(ctx, input.CsrfToken); err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(input.TaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	attachment, err := service.UploadTaskMedia(
		ctx,
		r.attachments,
		taskID,
		input.File.Filename,
		input.File.ContentType,
		input.File.Size,
		input.File.File,
	)
	if err != nil {
		return nil, r.mediaError(err, true)
	}
	return attachmentModel(attachment), nil
}

// TaskAttachments is the resolver for the taskAttachments field.
func (r *queryResolver) TaskAttachments(
	ctx context.Context, taskID string, page int,
) (*model.TaskAttachmentPage, error) {
	if _, err := requireSession(ctx); err != nil {
		return nil, err
	}
	id, err := parsePositiveID(taskID)
	if err != nil || page < 1 {
		return nil, clientError("VALIDATION_FAILED", "Task ID or page is invalid.")
	}
	result, err := r.attachments.TaskAttachments(ctx, id, int64(page))
	if err != nil {
		return nil, r.mediaError(err, false)
	}
	if result.TotalPages > math.MaxInt32 {
		return nil, clientError("UPSTREAM_REJECTED", "There are too many attachment pages.")
	}
	items := make([]*model.TaskAttachment, 0, len(result.Items))
	for _, attachment := range result.Items {
		items = append(items, attachmentModel(attachment))
	}
	return &model.TaskAttachmentPage{
		Items:      items,
		Page:       page,
		TotalPages: int(result.TotalPages),
		HasMore:    int64(page) < result.TotalPages,
	}, nil
}
