package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/RevoTale/vikunja-better-ui/internal/graphql/model"
	"github.com/RevoTale/vikunja-better-ui/internal/service"
	"github.com/RevoTale/vikunja-better-ui/internal/vikunja"
)

// SetTaskRelation is the resolver for the setTaskRelation field.
func (r *mutationResolver) SetTaskRelation(
	ctx context.Context, input model.SetTaskRelationInput,
) (*model.TaskRelationships, error) {
	if _, err := r.requireCSRF(ctx, input.CsrfToken); err != nil {
		return nil, err
	}
	baseID, err := parsePositiveID(input.TaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	otherID, err := parsePositiveID(input.OtherTaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Related task ID is invalid.")
	}
	kind := vikunja.RelationRelated
	if input.Kind == model.TaskRelationKindSubtask {
		kind = vikunja.RelationChild
	}
	if input.Kind == model.TaskRelationKindParent {
		kind = vikunja.RelationParent
	}
	if err := service.SetTaskRelation(ctx, r.tasks, r.relations, baseID, otherID, kind, input.Remove); err != nil {
		return nil, r.relationError(err)
	}
	return r.relationshipModel(ctx, baseID)
}

// TaskRelationships is the resolver for the taskRelationships field.
func (r *queryResolver) TaskRelationships(ctx context.Context, taskID string) (*model.TaskRelationships, error) {
	if _, err := requireSession(ctx); err != nil {
		return nil, err
	}
	id, err := parsePositiveID(taskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	return r.relationshipModel(ctx, id)
}

// RelationCandidates is the resolver for the relationCandidates field.
func (r *queryResolver) RelationCandidates(
	ctx context.Context, taskID string, search string, page int,
) (*model.RelationCandidatePage, error) {
	if _, err := requireSession(ctx); err != nil {
		return nil, err
	}
	id, err := parsePositiveID(taskID)
	if err != nil || page < 1 || len(search) > 250 {
		return nil, clientError("VALIDATION_FAILED", "Task search is invalid.")
	}
	result, err := service.FindRelationCandidates(ctx, r.tasks, id, search, int64(page))
	if err != nil {
		return nil, r.relationError(err)
	}
	items := make([]*model.RelatedTask, 0, len(result.Items))
	for _, task := range result.Items {
		items = append(items, relatedTaskModel(vikunja.RelatedTask{ID: task.ID, Title: task.Title, Done: task.Done}))
	}
	return &model.RelationCandidatePage{
		Items: items, Page: int(result.Page), HasMore: result.Page < result.TotalPages,
	}, nil
}
