package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"net/http"
	"strconv"
	"strings"
	"time"

	gqlgen "github.com/99designs/gqlgen/graphql"
	"github.com/RevoTale/vikunja-better-ui/internal/auth"
	"github.com/RevoTale/vikunja-better-ui/internal/concurrent"
	"github.com/RevoTale/vikunja-better-ui/internal/graphql/generated"
	"github.com/RevoTale/vikunja-better-ui/internal/graphql/model"
	"github.com/RevoTale/vikunja-better-ui/internal/service"
	"github.com/RevoTale/vikunja-better-ui/internal/vikunja"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	requestInfo, ok := auth.RequestInfoFromContext(ctx)
	if !ok {
		return nil, clientError("INTERNAL", "The request context is unavailable.")
	}
	if !r.limiter.Allow(requestInfo.ClientIP) {
		return nil, clientError("UNAUTHENTICATED", "Invalid username or password.")
	}
	if err := r.credentials.Verify(input.Username, input.Password); err != nil {
		r.limiter.RecordFailure(requestInfo.ClientIP)
		return nil, clientError("UNAUTHENTICATED", "Invalid username or password.")
	}
	user, err := r.users.CurrentUser(ctx)
	if err != nil {
		r.logError("verify Vikunja access during login", err)
		return nil, clientError("UPSTREAM_UNAVAILABLE", "Vikunja is unavailable. Try again shortly.")
	}
	token, session, err := r.sessions.Issue()
	if err != nil {
		r.logError("issue app session", err)
		return nil, clientError("INTERNAL", "The session could not be created.")
	}
	r.cookies.Set(requestInfo.Writer, token, session.ExpiresAt)
	r.limiter.RecordSuccess(requestInfo.ClientIP)
	return &model.LoginPayload{Session: authenticatedSession(r.sessions, session, user)}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, csrfToken string) (*model.LogoutPayload, error) {
	if _, err := r.requireCSRF(ctx, csrfToken); err != nil {
		return nil, err
	}
	requestInfo, ok := auth.RequestInfoFromContext(ctx)
	if !ok {
		return nil, clientError("INTERNAL", "The request context is unavailable.")
	}
	r.cookies.Clear(requestInfo.Writer)
	return &model.LogoutPayload{Authenticated: false}, nil
}

// CreateOneTimeTask is the resolver for the createOneTimeTask field.
func (r *mutationResolver) CreateOneTimeTask(ctx context.Context, input model.CreateOneTimeTaskInput) (*model.TaskMutationPayload, error) {
	session, err := r.requireCSRF(ctx, input.CsrfToken)
	if err != nil {
		return nil, err
	}
	user, projects, location, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	projectID, err := accessibleProject(input.ProjectID, projects)
	if err != nil {
		return nil, err
	}
	priority, err := priorityValue(input.Priority)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Choose a valid priority.")
	}
	write, dateOnly, err := service.BuildOneTimeTask(service.OneTimeInput{
		Title: input.Title, Description: optionalString(input.Description), Priority: priority,
		DueDate: optionalLocalDate(input.DueDate), DueTime: optionalLocalTime(input.DueTime),
	}, location)
	if err != nil {
		return nil, validationClientError(err)
	}
	marker := ""
	if dateOnly {
		marker = "vbu:date-only"
	}
	return r.createTaskPayload(ctx, session, user, projects, projectID, write, marker)
}

// CreateRecurringTask is the resolver for the createRecurringTask field.
func (r *mutationResolver) CreateRecurringTask(ctx context.Context, input model.CreateRecurringTaskInput) (*model.TaskMutationPayload, error) {
	session, err := r.requireCSRF(ctx, input.CsrfToken)
	if err != nil {
		return nil, err
	}
	user, projects, location, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	projectID, err := accessibleProject(input.ProjectID, projects)
	if err != nil {
		return nil, err
	}
	priority, err := priorityValue(input.Priority)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Choose a valid priority.")
	}
	write, dateOnly, err := service.BuildRecurringTask(service.RecurringInput{
		Title: input.Title, Description: optionalString(input.Description), Priority: priority,
		FirstDueDate: string(input.FirstDueDate), DueTime: optionalLocalTime(input.DueTime), Interval: input.Interval,
		Unit: service.RecurrenceUnit(input.Unit), Mode: service.RecurrenceMode(input.Mode),
		KeepDueTime: input.KeepDueTime,
	}, location)
	if err != nil {
		return nil, validationClientError(err)
	}
	marker := ""
	if dateOnly {
		marker = "vbu:date-only"
	} else if input.KeepDueTime {
		marker = "vbu:fixed-due-time"
	}
	return r.createTaskPayload(ctx, session, user, projects, projectID, write, marker)
}

// CreateJob is the resolver for the createJob field.
func (r *mutationResolver) CreateJob(ctx context.Context, input model.CreateJobInput) (*model.TaskMutationPayload, error) {
	session, err := r.requireCSRF(ctx, input.CsrfToken)
	if err != nil {
		return nil, err
	}
	user, projects, location, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	projectID, err := accessibleProject(input.ProjectID, projects)
	if err != nil {
		return nil, err
	}
	priority, err := priorityValue(input.Priority)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Choose a valid priority.")
	}
	write, err := service.BuildJobTask(service.JobInput{
		Title: optionalString(input.Title), Description: optionalString(input.Description), Priority: priority,
		StartLocal: string(input.StartAt), DurationMinutes: input.DurationMinutes,
		CompletionWindowMinutes: input.CompletionWindowMinutes,
	}, location)
	if err != nil {
		return nil, validationClientError(err)
	}
	return r.createTaskPayload(ctx, session, user, projects, projectID, write, "job")
}

// CompleteTask is the resolver for the completeTask field.
func (r *mutationResolver) CompleteTask(ctx context.Context, input model.CompleteTaskInput) (*model.CompletionPayload, error) {
	session, err := r.requireCSRF(ctx, input.CsrfToken)
	if err != nil {
		return nil, err
	}
	if input.ExpectedKind == model.TaskKindRecurring {
		return r.completeRecurringTask(ctx, session, input)
	}
	if input.ExpectedKind != model.TaskKindOneTime && input.ExpectedKind != model.TaskKindJob {
		return nil, clientError("INVALID_TASK_KIND", "This task cannot be completed from the app.")
	}
	user, projects, _, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(input.TaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	result, err := service.CompleteNonRecurring(
		ctx, r.tasks, r.capabilities, session.ID, taskID, service.TaskKind(input.ExpectedKind),
	)
	if err != nil {
		return nil, completionClientError(r.Resolver, err)
	}
	mapped, err := taskModel(
		result.Task, projectMap(projects), user.Settings.Timezone, r.now(), user.Settings.DefaultProjectID,
	)
	if err != nil {
		r.logError("map completed task", err)
		return nil, clientError("UPSTREAM_REJECTED", "The completed task uses unsupported fields.")
	}
	return &model.CompletionPayload{
		Status: model.CompletionStatusConfirmed, CompletedTask: mapped,
		UndoUntil: &result.UndoUntil, UndoCapability: &result.UndoCapability,
		MissingMarkers: []model.MarkerKind{}, RemainingRepairSteps: []model.RepairStep{},
	}, nil
}

// SkipRecurringTask is the resolver for the skipRecurringTask field.
func (r *mutationResolver) SkipRecurringTask(ctx context.Context, input model.SkipRecurringTaskInput) (*model.CompletionPayload, error) {
	session, err := r.requireCSRF(ctx, input.CsrfToken)
	if err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(input.TaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	user, projects, location, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	result, err := service.SkipRecurring(
		ctx, r.tasks, r.capabilities, taskID, input.ExpectedDueAt, location,
	)
	if err != nil {
		return nil, completionClientError(r.Resolver, err)
	}
	return r.recurringCompletionPayload(session, user, projects, result)
}

// SetRecurringKeepDueTime is the resolver for the setRecurringKeepDueTime field.
func (r *mutationResolver) SetRecurringKeepDueTime(
	ctx context.Context,
	input model.SetRecurringKeepDueTimeInput,
) (*model.TaskMutationPayload, error) {
	if _, err := r.requireCSRF(ctx, input.CsrfToken); err != nil {
		return nil, err
	}
	user, projects, _, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(input.TaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	task, err := service.SetFixedDueTime(ctx, r.tasks, taskID, input.Enabled)
	if err != nil {
		return nil, completionClientError(r.Resolver, err)
	}
	mapped, err := taskModel(
		task, projectMap(projects), user.Settings.Timezone, r.now(), user.Settings.DefaultProjectID,
	)
	if err != nil {
		return nil, clientError("UPSTREAM_REJECTED", "The updated task uses unsupported fields.")
	}
	return &model.TaskMutationPayload{
		Task: mapped, Status: model.TaskMutationStatusConfirmed,
		MissingMarkers: []model.MarkerKind{}, RemainingRepairSteps: []model.RepairStep{},
	}, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, input model.DeleteTaskInput) (*model.DeleteTaskPayload, error) {
	if _, err := r.requireCSRF(ctx, input.CsrfToken); err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(input.TaskID)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	_, projects, _, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	projectIDs := make([]int64, 0, len(projects))
	for _, project := range projects {
		projectIDs = append(projectIDs, project.ID)
	}
	if err := service.DeleteActiveTask(ctx, r.tasks, taskID, projectIDs); err != nil {
		return nil, deletionClientError(r.Resolver, err)
	}
	return &model.DeleteTaskPayload{DeletedTaskID: input.TaskID}, nil
}

// UndoTaskCompletion is the resolver for the undoTaskCompletion field.
func (r *mutationResolver) UndoTaskCompletion(ctx context.Context, input model.UndoTaskCompletionInput) (*model.TaskMutationPayload, error) {
	session, err := r.requireCSRF(ctx, input.CsrfToken)
	if err != nil {
		return nil, err
	}
	user, projects, _, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	task, err := service.UndoNonRecurring(ctx, r.tasks, r.capabilities, session.ID, input.Capability)
	if err != nil {
		return nil, completionClientError(r.Resolver, err)
	}
	mapped, err := taskModel(task, projectMap(projects), user.Settings.Timezone, r.now(), user.Settings.DefaultProjectID)
	if err != nil {
		return nil, clientError("UPSTREAM_REJECTED", "The restored task uses unsupported fields.")
	}
	return &model.TaskMutationPayload{
		Task: mapped, Status: model.TaskMutationStatusConfirmed,
		MissingMarkers: []model.MarkerKind{}, RemainingRepairSteps: []model.RepairStep{},
	}, nil
}

// RepairTaskMetadata is the resolver for the repairTaskMetadata field.
func (r *mutationResolver) RepairTaskMetadata(ctx context.Context, input model.RepairTaskMetadataInput) (*model.TaskMutationPayload, error) {
	session, err := r.requireCSRF(ctx, input.CsrfToken)
	if err != nil {
		return nil, err
	}
	user, projects, _, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	if strings.HasPrefix(input.Capability, "rr.") {
		return r.repairRecurringSnapshot(ctx, session, user, projects, input.Capability)
	}
	result, err := service.RepairMarker(ctx, r.tasks, r.capabilities, session.ID, input.Capability)
	if err != nil {
		return nil, completionClientError(r.Resolver, err)
	}
	mapped, err := taskModel(result.Task, projectMap(projects), user.Settings.Timezone, r.now(), user.Settings.DefaultProjectID)
	if err != nil {
		return nil, clientError("UPSTREAM_REJECTED", "The repaired task uses unsupported fields.")
	}
	payload := &model.TaskMutationPayload{
		Task: mapped, Status: model.TaskMutationStatusConfirmed,
		MissingMarkers: []model.MarkerKind{}, RemainingRepairSteps: []model.RepairStep{},
	}
	if !result.Complete {
		grant, parseErr := r.capabilities.ParseMarkerRepair(session.ID, result.Capability)
		if parseErr != nil {
			return nil, clientError("INTERNAL", "Task repair could not be continued.")
		}
		marker, step := markerModels(grant.MarkerTitle)
		payload.Status = model.TaskMutationStatusRepairRequired
		payload.MissingMarkers = []model.MarkerKind{marker}
		payload.RemainingRepairSteps = []model.RepairStep{step}
		payload.RepairCapability = &result.Capability
	}
	return payload, nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context) (*model.Session, error) {
	session, ok := auth.SessionFromContext(ctx)
	if !ok {
		return &model.Session{Authenticated: false}, nil
	}
	result := authenticatedSessionWithoutUser(r.sessions, session)
	if !gqlgen.FieldRequested(ctx, "vikunjaUser") {
		return result, nil
	}
	user, err := r.users.CurrentUser(ctx)
	if err != nil {
		r.logError("read Vikunja user for session", err)
		return nil, clientError("UPSTREAM_UNAVAILABLE", "Vikunja is unavailable. Try again shortly.")
	}
	result.VikunjaUser = vikunjaUserModel(user)
	return result, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) (*model.ProjectResult, error) {
	if _, err := requireSession(ctx); err != nil {
		return nil, err
	}
	metadata := r.loadQueryMetadata(ctx)
	if metadata.userErr != nil {
		r.logError("read Vikunja user for projects", metadata.userErr)
		return nil, clientError("UPSTREAM_UNAVAILABLE", "Vikunja is unavailable. Try again shortly.")
	}
	if metadata.projectsErr != nil {
		r.logError("read Vikunja projects", metadata.projectsErr)
		return nil, clientError("UPSTREAM_UNAVAILABLE", "Vikunja projects could not be loaded.")
	}
	items := make([]*model.Project, 0, len(metadata.projects))
	for _, project := range metadata.projects {
		items = append(items, &model.Project{
			ID: strconv.FormatInt(project.ID, 10), Title: project.Title,
			IsDefault: project.ID == metadata.user.Settings.DefaultProjectID,
		})
	}
	return &model.ProjectResult{Items: items}, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, input model.TaskListInput) (*model.TaskPage, error) {
	if _, err := requireSession(ctx); err != nil {
		return nil, err
	}
	includeLabels := input.Scope == model.TaskScopeJobs
	userRead := concurrent.Start(func() (vikunja.User, error) { return r.users.CurrentUser(ctx) })
	projectsRead := concurrent.Start(func() ([]vikunja.Project, error) { return r.projects.Projects(ctx) })
	var labelsRead *concurrent.Future[[]vikunja.Label]
	if includeLabels {
		labelsRead = concurrent.Start(func() ([]vikunja.Label, error) { return r.tasks.Labels(ctx) })
	}

	user, userErr := userRead.Wait()
	location, err := r.taskLocation(user, userErr)
	if err != nil {
		return nil, err
	}
	var jobLabelIDs []int64
	if includeLabels {
		labels, labelsErr := labelsRead.Wait()
		if labelsErr != nil {
			r.logError("resolve job marker labels", labelsErr)
			return nil, upstreamClientError(labelsErr, "Job markers could not be loaded.")
		}
		jobLabelIDs = service.ExactLabelIDs(labels, "job")
	}

	var projects []vikunja.Project
	needsProjectsBeforeTasks := input.ProjectID != nil || input.Scope == model.TaskScopeUnscheduled
	if needsProjectsBeforeTasks {
		projects, err = r.waitForTaskProjects(projectsRead)
		if err != nil {
			return nil, err
		}
	}
	selectedProjectID, err := selectedProject(input.ProjectID, projects)
	if err != nil {
		return nil, err
	}
	projectTitles := projectTitleMap(projects)
	result, err := service.ListTasks(ctx, r.tasks, service.ListRequest{
		Scope: service.TaskScope(input.Scope), ProjectID: selectedProjectID,
		Page: input.Page, PageSize: input.PageSize, Now: r.now(),
		Location: location, Timezone: user.Settings.Timezone,
		WeekStart: time.Weekday(user.Settings.WeekStart), ProjectTitles: projectTitles,
		JobLabelIDs: jobLabelIDs,
	})
	if err != nil {
		r.logError("list tasks", err)
		return nil, upstreamClientError(err, "Tasks could not be loaded.")
	}
	if !needsProjectsBeforeTasks {
		projects, err = r.waitForTaskProjects(projectsRead)
		if err != nil {
			return nil, err
		}
	}
	return r.taskPageModel(result, projects, user)
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	user, projects, _, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(id)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	task, _, err := r.tasks.Task(ctx, taskID)
	if err != nil {
		if isUpstreamStatus(err, http.StatusNotFound) {
			return nil, nil
		}
		r.logError("read task", err)
		return nil, upstreamClientError(err, "The task could not be loaded.")
	}
	mapped, err := taskModel(task, projectMap(projects), user.Settings.Timezone, r.now(), user.Settings.DefaultProjectID)
	if err != nil {
		r.logError("map task", err)
		return nil, clientError("UPSTREAM_REJECTED", "The task uses fields this client cannot represent.")
	}
	return mapped, nil
}

// TaskDiagnostics is the resolver for the taskDiagnostics field.
func (r *queryResolver) TaskDiagnostics(ctx context.Context, id string) (*model.TaskDiagnostics, error) {
	user, projects, _, err := r.taskContext(ctx)
	if err != nil {
		return nil, err
	}
	taskID, err := parsePositiveID(id)
	if err != nil {
		return nil, clientError("VALIDATION_FAILED", "Task ID is invalid.")
	}
	task, _, err := r.tasks.Task(ctx, taskID)
	if err != nil {
		if isUpstreamStatus(err, http.StatusNotFound) {
			return nil, nil
		}
		r.logError("read task diagnostics", err)
		return nil, upstreamClientError(err, "Task diagnostics could not be loaded.")
	}
	if _, ok := projectMap(projects)[task.ProjectID]; !ok {
		return nil, clientError("FORBIDDEN", "The task project is not accessible.")
	}
	return diagnosticsModel(task, user.Settings.Timezone)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

func authenticatedSession(manager *auth.SessionManager, session auth.Session, user vikunja.User) *model.Session {
	result := authenticatedSessionWithoutUser(manager, session)
	result.VikunjaUser = vikunjaUserModel(user)
	return result
}

func authenticatedSessionWithoutUser(manager *auth.SessionManager, session auth.Session) *model.Session {
	csrfToken := manager.CSRFToken(session)
	expiresAt := session.ExpiresAt
	return &model.Session{
		Authenticated: true, CsrfToken: &csrfToken, ExpiresAt: &expiresAt,
	}
}

func vikunjaUserModel(user vikunja.User) *model.VikunjaUser {
	var defaultProjectID *string
	if user.Settings.DefaultProjectID > 0 {
		value := strconv.FormatInt(user.Settings.DefaultProjectID, 10)
		defaultProjectID = &value
	}
	return &model.VikunjaUser{
		ID: strconv.FormatInt(user.ID, 10), Username: user.Username,
		Timezone: user.Settings.Timezone, WeekStart: user.Settings.WeekStart,
		DefaultProjectID: defaultProjectID,
	}
}

func requireSession(ctx context.Context) (auth.Session, error) {
	session, ok := auth.SessionFromContext(ctx)
	if !ok {
		return auth.Session{}, clientError("UNAUTHENTICATED", "Log in to continue.")
	}
	return session, nil
}

func (r *Resolver) requireCSRF(ctx context.Context, inputToken string) (auth.Session, error) {
	session, err := requireSession(ctx)
	if err != nil {
		return auth.Session{}, err
	}
	requestInfo, ok := auth.RequestInfoFromContext(ctx)
	if !ok {
		return auth.Session{}, clientError("INTERNAL", "The request context is unavailable.")
	}
	headerToken := requestInfo.Request.Header.Get("X-CSRF-Token")
	if inputToken == "" || inputToken != headerToken || !r.sessions.VerifyCSRF(session, inputToken) {
		return auth.Session{}, clientError("CSRF_INVALID", "Refresh the page and try again.")
	}
	return session, nil
}
