/* biome-ignore-all lint: generated by TanStack Router */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated.jobs'
import { Route as AuthenticatedMonthRouteImport } from './routes/_authenticated.month'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated.today'
import { Route as AuthenticatedUnscheduledRouteImport } from './routes/_authenticated.unscheduled'
import { Route as AuthenticatedWeekRouteImport } from './routes/_authenticated.week'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated.tasks.$taskId'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated.tasks.new'
import { Route as AuthenticatedTasksTaskIdIndexRouteImport } from './routes/_authenticated.tasks.$taskId.index'
import { Route as AuthenticatedTasksTaskIdExtendedRouteImport } from './routes/_authenticated.tasks.$taskId.extended'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonthRoute = AuthenticatedMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnscheduledRoute =
  AuthenticatedUnscheduledRouteImport.update({
    id: '/unscheduled',
    path: '/unscheduled',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWeekRoute = AuthenticatedWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksTaskIdIndexRoute =
  AuthenticatedTasksTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTasksTaskIdRoute,
  } as any)
const AuthenticatedTasksTaskIdExtendedRoute =
  AuthenticatedTasksTaskIdExtendedRouteImport.update({
    id: '/extended',
    path: '/extended',
    getParentRoute: () => AuthenticatedTasksTaskIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/month': typeof AuthenticatedMonthRoute
  '/today': typeof AuthenticatedTodayRoute
  '/unscheduled': typeof AuthenticatedUnscheduledRoute
  '/week': typeof AuthenticatedWeekRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRouteWithChildren
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/tasks/$taskId/extended': typeof AuthenticatedTasksTaskIdExtendedRoute
  '/tasks/$taskId/': typeof AuthenticatedTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/month': typeof AuthenticatedMonthRoute
  '/today': typeof AuthenticatedTodayRoute
  '/unscheduled': typeof AuthenticatedUnscheduledRoute
  '/week': typeof AuthenticatedWeekRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/tasks/$taskId/extended': typeof AuthenticatedTasksTaskIdExtendedRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/month': typeof AuthenticatedMonthRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/unscheduled': typeof AuthenticatedUnscheduledRoute
  '/_authenticated/week': typeof AuthenticatedWeekRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRouteWithChildren
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
  '/_authenticated/tasks/$taskId/extended': typeof AuthenticatedTasksTaskIdExtendedRoute
  '/_authenticated/tasks/$taskId/': typeof AuthenticatedTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/history'
    | '/jobs'
    | '/month'
    | '/today'
    | '/unscheduled'
    | '/week'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tasks/$taskId/extended'
    | '/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/history'
    | '/jobs'
    | '/month'
    | '/today'
    | '/unscheduled'
    | '/week'
    | '/tasks/new'
    | '/tasks/$taskId/extended'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/history'
    | '/_authenticated/jobs'
    | '/_authenticated/month'
    | '/_authenticated/today'
    | '/_authenticated/unscheduled'
    | '/_authenticated/week'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/tasks/new'
    | '/_authenticated/tasks/$taskId/extended'
    | '/_authenticated/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/month': {
      id: '/_authenticated/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof AuthenticatedMonthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/unscheduled': {
      id: '/_authenticated/unscheduled'
      path: '/unscheduled'
      fullPath: '/unscheduled'
      preLoaderRoute: typeof AuthenticatedUnscheduledRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/week': {
      id: '/_authenticated/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthenticatedWeekRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/$taskId/': {
      id: '/_authenticated/tasks/$taskId/'
      path: '/'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdIndexRouteImport
      parentRoute: typeof AuthenticatedTasksTaskIdRoute
    }
    '/_authenticated/tasks/$taskId/extended': {
      id: '/_authenticated/tasks/$taskId/extended'
      path: '/extended'
      fullPath: '/tasks/$taskId/extended'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdExtendedRouteImport
      parentRoute: typeof AuthenticatedTasksTaskIdRoute
    }
  }
}

interface AuthenticatedTasksTaskIdRouteChildren {
  AuthenticatedTasksTaskIdExtendedRoute: typeof AuthenticatedTasksTaskIdExtendedRoute
  AuthenticatedTasksTaskIdIndexRoute: typeof AuthenticatedTasksTaskIdIndexRoute
}

const AuthenticatedTasksTaskIdRouteChildren: AuthenticatedTasksTaskIdRouteChildren =
  {
    AuthenticatedTasksTaskIdExtendedRoute:
      AuthenticatedTasksTaskIdExtendedRoute,
    AuthenticatedTasksTaskIdIndexRoute: AuthenticatedTasksTaskIdIndexRoute,
  }

const AuthenticatedTasksTaskIdRouteWithChildren =
  AuthenticatedTasksTaskIdRoute._addFileChildren(
    AuthenticatedTasksTaskIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedMonthRoute: typeof AuthenticatedMonthRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedUnscheduledRoute: typeof AuthenticatedUnscheduledRoute
  AuthenticatedWeekRoute: typeof AuthenticatedWeekRoute
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRouteWithChildren
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedMonthRoute: AuthenticatedMonthRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedUnscheduledRoute: AuthenticatedUnscheduledRoute,
  AuthenticatedWeekRoute: AuthenticatedWeekRoute,
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRouteWithChildren,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
